services:
  build:
    build:
      context: game-page
      dockerfile: Dockerfile
    command: npm run build
    volumes:
      - ./game-page:/app/game-page
      - /app/game-page/node_modules
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    ports:
      - "443:80"
    volumes:
      - ./game-page/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - build
