services:
  game-page:
    build:
      context: game-page
      dockerfile: Dockerfile
    command: npm run build
    volumes:
      - ./game-page:/app/game-page
      - /app/game-page/node_modules
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./game-page/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/superxo.fun/fullchain.pem:/etc/letsencrypt/live/superxo.fun/fullchain.pem
      - /etc/letsencrypt/live/superxo.fun/privkey.pem:/etc/letsencrypt/live/superxo.fun/privkey.pem
    depends_on:
      game-page:
        condition: service_completed_successfully

  middleware:
    build:
        context: middleware
    command: ["--port", ":8080"]
    ports:
        - "2052:8080"
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./middleware/init-db:/docker-entrypoint-initdb.d

  solver:
    build:
        context: solver
    ports:
        - "18080:18080"

volumes:
  db-data:
