services:
  game-page:
    build:
      context: game-page
      dockerfile: Dockerfile
    command: npm run build
    volumes:
      - ./game-page:/app/game-page
      - /app/game-page/node_modules
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./game-page/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/superxo.fun/fullchain.pem:/etc/letsencrypt/live/superxo.fun/fullchain.pem
      - /etc/letsencrypt/live/superxo.fun/privkey.pem:/etc/letsencrypt/live/superxo.fun/privkey.pem
    depends_on:
      game-page:
        condition: service_completed_successfully

  middleware:
    build:
        context: middleware
    command: ["--port", ":8080"]
    ports:
        - "127.0.0.1:2052:8080"
    environment:
          DB_HOST: db
          DB_PORT: 5432
          DB_USER: ${DB_USER:-postgres}
          DB_PASSWORD: ${DB_PASSWORD:-postgres}
          DB_NAME: ${DB_NAME:-games}
          DB_SSL_MODE: disable
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-games}
      PGDATA: /var/lib/postgresql/data/pgdata_games
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./middleware/init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d games" ]
      interval: 10s
      timeout: 5s
      retries: 3

  solver:
    build:
        context: solver
    ports:
        - "127.0.0.1:18080:18080"

volumes:
  pgdata:
    driver: local
