CREATE TABLE IF NOT EXISTS games (
    id VARCHAR(10) NOT NULL PRIMARY KEY,
    player1 VARCHAR(10),
    player2 VARCHAR(10),
    moves TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_move TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
